// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  Whether ForeverBuddy is installed in the active game folder, its version
	 *  against the one this app carries, and which characters have it on.
	 */
	addonStatus: () => __TAURI_INVOKE<AddonStatus>("addon_status"),
	/**
	 *  Installs or updates the addon through the write gate: refused while WoW
	 *  runs, with a safety snapshot first. Runs as the one backup/restore job.
	 */
	addonInstall: () => __TAURI_INVOKE<AddonStatus>("addon_install"),
	/**
	 *  Removes the addon's files (and its folder, if nothing else is in it).
	 *  The SavedVariables stay: they're the player's data.
	 */
	addonRemove: () => __TAURI_INVOKE<AddonStatus>("addon_remove"),
	/**
	 *  The Addons screen (F4): every addon in the active flavor's
	 *  `Interface/AddOns`, read-only, with each character's on/off. `null`
	 *  before a game folder is set.
	 */
	addonsList: () => __TAURI_INVOKE<{
	/**
	 *  The flavor folder, e.g. `_classic_beta_`, and its display name
	 *  ("WoW: Forever (Beta)"), for the lede.
	 */
	flavor: string,
	game: string,
	/**  The flavor's `Interface/AddOns` (full path). */
	folder: string,
	/**
	 *  The interface number this client reads (`16001` on Forever), from its
	 *  version; `None` when the version isn't known.
	 */
	interface: number | null,
	/**
	 *  The characters the "Enabled for" columns are for, in the Characters
	 *  screen's order (the WTF roster, older settings folders left out).
	 */
	characters: AddonCharacter[],
	/**  Sorted by title. */
	addons: AddonInfo[],
	/**  When this was read (RFC 3339). */
	read_at: string,
} | null>("addons_list"),
	/**
	 *  Applies the staged addon switches (F6) by rewriting the characters'
	 *  AddOns.txt through the write gate: refused while WoW runs, with one
	 *  safety snapshot first. Every addon and character is checked against what
	 *  the list shows; nothing else can be named. Runs as the one backup/restore
	 *  job.
	 */
	addonsApply: (changes: AddonChange[]) => __TAURI_INVOKE<ToggleResult>("addons_apply", { changes }),
	/**
	 *  Undoes a toggle from its safety snapshot (`ToggleResult::snapshot_id`):
	 *  only AddOns.txt files are put back, through the write gate.
	 */
	addonsUndo: (snapshotId: string) => __TAURI_INVOKE<null>("addons_undo", { snapshotId }),
	/**
	 *  One adventure's recap, or the newest one when `id` is `None`. `None`
	 *  back means there are no adventures yet (or none with that id).
	 */
	adventureGet: (id: number | null) => __TAURI_INVOKE<{
	id: number,
	character_id: number,
	name: string,
	/**  File tokens, e.g. "WARRIOR" and "Human". */
	class: string | null,
	race: string | null,
	/**  RFC 3339, UTC. */
	login: string,
	logout: string | null,
	played_secs: number | null,
	/**
	 *  The zone or instance with the most time, or the top two joined
	 *  ("Stratholme & Eastern Plaguelands") when the second had at least
	 *  half as long.
	 */
	title: string,
	level_start: number | null,
	level_end: number | null,
	/**  Where the character logged out. */
	last_zone: string | null,
	/**  Zones in the order first visited. */
	travelled: string[],
	tally: Tally,
	/**  Gold through the session: login, every money point, logout. */
	money: MoneyPoint[],
	/**  Deaths, bosses, level-ups and quests, for the money chart. */
	markers: Marker[],
	timeline: Line[],
	gained: ItemLine[],
	spent: ItemLine[],
	quests: QuestLine[],
	note: string | null,
	/**  The adventures before and after this one, across characters. */
	prev: AdventureLink | null,
	next: AdventureLink | null,
} | null>("adventure_get", { id }),
	/**
	 *  Saves the user's note on an adventure (blank clears it). Only the app's
	 *  own database changes; nothing is written to the game folder.
	 */
	adventureSetNote: (id: number, note: string) => __TAURI_INVOKE<null>("adventure_set_note", { id, note }),
	/**  App version and data locations, for the Settings/about panel and bug reports. */
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	/**
	 *  The Ledger for the active flavor: tiles, the daily gold chart and the
	 *  journal, over `range`, in the user's time zone.
	 */
	ledgerGet: (range: LedgerRange) => __TAURI_INVOKE<Ledger>("ledger_get", { range }),
	/**
	 *  "Export CSV": the gold table or the journal, to `dest` from the save
	 *  dialog (never inside the game or backup folders). Returns the path
	 *  written, with `.csv` added if it was missing.
	 */
	ledgerExportCsv: (range: LedgerRange, kind: LedgerExport, dest: string) => __TAURI_INVOKE<string>("ledger_export_csv", { range, kind, dest }),
	/**
	 *  The Macros screen (F7): every account's and character's macros in the
	 *  active flavor, read-only. `null` before a game folder is set.
	 */
	macrosList: () => __TAURI_INVOKE<{
	/**  The flavor folder, e.g. `_classic_beta_`. */
	flavor: string,
	/**  One per account folder, in name order. */
	accounts: AccountMacros[],
	/**
	 *  One per character on the WTF roster (older settings folders left
	 *  out), in the Characters screen's order, macros or not.
	 */
	characters: CharacterMacros[],
	/**  The longest body the game allows. */
	max: number,
} | null>("macros_list"),
	/**
	 *  The scan bar: whether there are prices, how many, and when Auctionator
	 *  last scanned.
	 */
	ahStatus: () => __TAURI_INVOKE<AhStatus>("ah_status"),
	/**  Priced items whose name contains `query` (or with that item id). */
	ahSearch: (query: string) => __TAURI_INVOKE<AhItem[]>("ah_search", { query }),
	/**  One item's price history over the last `days` (all of it with `None`). */
	ahHistory: (itemId: number, days: number | null) => __TAURI_INVOKE<AhHistory>("ah_history", { itemId, days }),
	ahWatchlist: () => __TAURI_INVOKE<AhItem[]>("ah_watchlist"),
	/**
	 *  Adds an item to the watchlist, or removes it. The app's own list: never
	 *  written to the game.
	 */
	ahSetWatched: (itemId: number, watched: boolean) => __TAURI_INVOKE<null>("ah_set_watched", { itemId, watched }),
	/**  What the alts carry that's worth at least `min_value` copper. */
	ahWorthSelling: (minValue: number | null) => __TAURI_INVOKE<Sellable[]>("ah_worth_selling", { minValue }),
	/**
	 *  Net worth's goods (F5c): what the alts carry, valued at the last scan,
	 *  priced items only.
	 */
	ahGoodsWorth: () => __TAURI_INVOKE<GoodsWorth>("ah_goods_worth"),
	/**  The last lowest buyout of each item that has one, as `(id, copper)`. */
	ahPrices: (itemIds: number[]) => __TAURI_INVOKE<([number, number | null])[]>("ah_prices", { itemIds }),
	/**
	 *  The latest automatic backup failure, if no automatic backup has
	 *  succeeded since. The UI asks on start, since a failure can happen before
	 *  it's listening.
	 */
	backupAutoStatus: () => __TAURI_INVOKE<{
	/**  RFC 3339, UTC. */
	at: string,
	trigger: Trigger,
	/**  The error, as shown to the user. */
	error: string,
	/**
	 *  0: the backup failed. Otherwise it was taken, but this many files
	 *  couldn't be read and were left out.
	 */
	skipped?: number,
} | null>("backup_auto_status"),
	/**
	 *  "Back up now": a full manual snapshot. Allowed while WoW runs, and then
	 *  flagged as taken mid-session. Waits if another backup or restore is running.
	 */
	backupCreate: (label: string | null) => __TAURI_INVOKE<SnapshotSummary>("backup_create", { label }),
	/**
	 *  Refused for a snapshot an interrupted restore still needs, and while the
	 *  restore journal is unreadable (then nobody can tell which those are).
	 *  Runs as a job, so it can't race a restore that's starting from the same
	 *  snapshot before its journal is written; it waits behind a running backup.
	 */
	backupDelete: (id: string) => __TAURI_INVOKE<null>("backup_delete", { id }),
	/**
	 *  "Export as .zip". `dest` comes from the save dialog; it may not be inside
	 *  the game folder (or a linked folder's target) or the backup store. Runs
	 *  as the one backup/restore job, so pruning can't remove the snapshot
	 *  mid-export.
	 */
	backupExportZip: (id: string, dest: string) => __TAURI_INVOKE<ExportReport>("backup_export_zip", { id, dest }),
	/**  One snapshot, grouped by account, character and category for the restore panel. */
	backupGet: (id: string) => __TAURI_INVOKE<SnapshotDetail>("backup_get", { id }),
	/**  Every snapshot, newest first. */
	backupList: () => __TAURI_INVOKE<SnapshotSummary[]>("backup_list"),
	/**
	 *  Settings' "Prune now". Waits for any running backup or restore, because
	 *  garbage collection must never overlap one. Keeps whatever an interrupted
	 *  restore still needs, and refuses while its journal is unreadable.
	 */
	backupPruneNow: () => __TAURI_INVOKE<PruneReport>("backup_prune_now"),
	/**
	 *  Settings' "Store backups in": moves the store to a picked folder (into
	 *  its own subfolder there), or back to the default with `None`, and points
	 *  the setting at it. Waits for any running backup or restore. Emits
	 *  `MoveProgress` while it copies.
	 */
	backupMoveLocation: (location: string | null) => __TAURI_INVOKE<MoveReport>("backup_move_location", { location }),
	backupSetLabel: (id: string, label: string | null) => __TAURI_INVOKE<SnapshotSummary>("backup_set_label", { id, label }),
	backupSetPinned: (id: string, pinned: boolean) => __TAURI_INVOKE<SnapshotSummary>("backup_set_pinned", { id, pinned }),
	/**  The storage meter and the retention sentence for the Backups header. */
	backupStorage: () => __TAURI_INVOKE<StorageInfo>("backup_storage"),
	/**
	 *  What restoring `selection` from snapshot `id` would do: files to write
	 *  (per folder), files to delete, unchanged and read-only files, and a
	 *  one-line summary. Changes nothing.
	 */
	backupRestorePreview: (id: string, selection: RestoreSelection, mode: "overlay" | "mirror" | null) => __TAURI_INVOKE<RestorePlan>("backup_restore_preview", { id, selection, mode }),
	/**
	 *  Restores `selection` from snapshot `id`. `confirmed_deletes` is the
	 *  preview's `delete` list the user confirmed. Fails before changing anything
	 *  with `GameRunning` while WoW runs (the UI waits for it to close, then the
	 *  user confirms again), `ReadOnly`, `BackupCorrupt`, `RestorePending`, or
	 *  `DeletionsChanged` if it would remove a file not in `confirmed_deletes`.
	 *  Waits for any running backup or restore.
	 */
	backupRestore: (id: string, selection: RestoreSelection, mode: "overlay" | "mirror" | null, confirmedDeletes: RelPath[]) => __TAURI_INVOKE<RestoreReport>("backup_restore", { id, selection, mode, confirmedDeletes }),
	/**
	 *  Checks every stored copy in a snapshot against its checksum. Runs as a
	 *  job, so a concurrent prune's GC can't remove blobs mid-check and make
	 *  them look missing.
	 */
	backupVerify: (id: string) => __TAURI_INVOKE<VerifyReport>("backup_verify", { id }),
	/**
	 *  Whether a restore was interrupted, for the startup recovery dialog and the
	 *  "restores locked" banner. `unreadable` carries the newest pre-restore
	 *  safety snapshot for "Open the safety copy", since the journal can't say.
	 */
	restoreJournalStatus: () => __TAURI_INVOKE<RecoveryStatus>("restore_journal_status"),
	/**
	 *  What rolling back or finishing the interrupted restore would do, for the
	 *  recovery dialog's confirm step. Changes nothing. Discard has no plan.
	 */
	restoreJournalPreview: (action: JournalAction) => __TAURI_INVOKE<RestorePlan>("restore_journal_preview", { action }),
	/**
	 *  Rolls back, finishes or discards an interrupted restore. Until one of
	 *  these succeeds, `backup_restore` is refused with `RestorePending`.
	 *  `confirmed_deletes` is `restore_journal_preview`'s `delete` list the user
	 *  confirmed; roll back and finish are refused with `DeletionsChanged` if
	 *  they would remove anything else. Discard ignores it.
	 */
	restoreJournalResolve: (action: JournalAction, confirmedDeletes: RelPath[]) => __TAURI_INVOKE<RestoreReport>("restore_journal_resolve", { action, confirmedDeletes }),
	/**
	 *  Whether WoW is running, as of the last poll (every 2 s). The UI calls this
	 *  on mount, then follows `game-status-changed`.
	 */
	gameStatus: () => __TAURI_INVOKE<GameStatus>("game_status"),
	/**
	 *  Settings > Game data cache: how many icons are cached, their size, and
	 *  the build they came from (unknown while item icons are off: even the
	 *  build files aren't read then).
	 */
	iconsCacheStatus: () => __TAURI_INVOKE<IconCacheStatus>("icons_cache_status"),
	/**
	 *  "Rebuild": empties the cache and reads every known item's icon again.
	 *  Refused while item icons are off.
	 */
	iconsCacheRebuild: () => __TAURI_INVOKE<IconFill>("icons_cache_rebuild"),
	/**  "Clear": empties the cache. Icons are read again as they're shown. */
	iconsCacheClear: () => __TAURI_INVOKE<null>("icons_cache_clear"),
	/**
	 *  Play sessions of the active flavor from the last `days` days, newest
	 *  first. The one with no `ended_at` is in progress. Follow
	 *  `sessions-changed` for updates.
	 */
	sessionsList: (days: number) => __TAURI_INVOKE<PlaySession[]>("sessions_list", { days }),
	/**
	 *  The characters in the active flavor's WTF folder, most recently played
	 *  first. Names only: class, level and gold need the addon (v0.2).
	 */
	charactersList: () => __TAURI_INVOKE<WtfCharacter[]>("characters_list"),
	/**
	 *  Characters whose ForeverBuddy notes couldn't be read last time, for the
	 *  Dashboard's "Couldn't read Thrandor's notes · will retry". They're retried
	 *  when the file changes. Only the active flavor's; none before a game
	 *  folder is set.
	 */
	ingestProblems: () => __TAURI_INVOKE<IngestProblem[]>("ingest_problems"),
	/**
	 *  The Characters screen: totals and one card per character of the active
	 *  game flavor. Empty (not an error) before a game folder is set.
	 */
	charactersOverview: () => __TAURI_INVOKE<CharactersOverview>("characters_overview"),
	/**  One character's sheet: gear, satchels, bank, mail, professions, 30-day gold. */
	characterDetail: (id: number) => __TAURI_INVOKE<CharacterSheet>("character_detail", { id }),
	/**
	 *  The Characters search box: every satchel, bank and mailbox of the active
	 *  flavor's characters, searched by item name words and `ilvl>60`-style
	 *  filters. Nothing before a game folder is set.
	 */
	charactersSearch: (query: string) => __TAURI_INVOKE<SearchResults>("characters_search", { query }),
	/**
	 *  Raid and dungeon saves across the active flavor's characters that haven't
	 *  reset yet, soonest first (the Dashboard's "Lockouts this week"). Empty
	 *  before a game folder is set.
	 */
	lockoutsList: () => __TAURI_INVOKE<AltLockout[]>("lockouts_list"),
	/**  Marks or unmarks a character as a bank alt (its card's "Bank" tag). */
	characterSetBankAlt: (id: number, bankAlt: boolean) => __TAURI_INVOKE<null>("character_set_bank_alt", { id, bankAlt }),
	/**
	 *  One character's quest log (Q1b): completed count and recent accepts and
	 *  turn-ins. The sheet shows it only when it has something in it.
	 */
	characterQuests: (id: number) => __TAURI_INVOKE<QuestLog>("character_quests", { id }),
	/**
	 *  Whether any character has quest data yet; until then the sheet's Quests
	 *  tab stays hidden. False before a game folder is set.
	 */
	questsAvailable: () => __TAURI_INVOKE<boolean>("quests_available"),
	settingsGet: () => __TAURI_INVOKE<Settings>("settings_get"),
	/**
	 *  Changes only the fields present in `patch` and returns the new settings.
	 *  The game folder isn't part of it: that goes through the install
	 *  commands, which validate it. Nor is the backup location, which moves the
	 *  backups (`backup_move_location`).
	 *  Runs off the main thread: validation resolves the backup location, which
	 *  can stall on an offline network share.
	 */
	settingsUpdate: (patch: SettingsPatch_Deserialize) => __TAURI_INVOKE<Settings>("settings_update", { patch }),
	/**
	 *  Which integration keys are set, with a per-row error if one can't be
	 *  read. Never returns the values.
	 */
	secretsStatus: () => __TAURI_INVOKE<SecretStatus[]>("secrets_status"),
	/**  Stores a key (trimmed). There is no command to read it back. */
	secretsSet: (id: IntegrationId, value: string) => __TAURI_INVOKE<null>("secrets_set", { id, value }),
	secretsDelete: (id: IntegrationId) => __TAURI_INVOKE<null>("secrets_delete", { id }),
	/**
	 *  Every WoW install found (the saved one first, then registry and common
	 *  paths, each with its source), plus every place we looked.
	 */
	installDetect: () => __TAURI_INVOKE<DetectReport>("install_detect"),
	/**
	 *  The active install, re-validated. Fails with `InvalidInstall` if the saved
	 *  folder is gone, and is `null` if none has been chosen.
	 */
	installGet: () => __TAURI_INVOKE<{
	root: string,
	flavors: Flavor[],
	/**  Folder name of the active flavor, once one is chosen. */
	active: string | null,
} | null>("install_get"),
	/**
	 *  Sets the install from a picked folder (root, flavor folder or WTF) and
	 *  optionally a flavor id. Validates, normalizes and saves. Waits for any
	 *  running backup or restore (it sweeps temp files in WTF).
	 */
	installSet: (path: string, flavor: string | null) => __TAURI_INVOKE<Install>("install_set", { path, flavor }),
	/**
	 *  Opens one of the app's folders in Explorer/Finder. The opening happens in
	 *  Rust, so the webview needs no opener permissions at all.
	 */
	appOpenFolder: (which: FolderTarget) => __TAURI_INVOKE<null>("app_open_folder", { which }),
	/**
	 *  Why the app couldn't start, or `null` when it started fine. The UI asks
	 *  this first: in the failure case no other command has state to work with.
	 */
	startupFailure: () => __TAURI_INVOKE<{
	problem: StartupProblem,
	/**  The error, for "Error details" and "Copy error details". */
	message: string,
	paths: AppPaths,
	/**  The file at fault, shown in red; `None` if it isn't one file. */
	at_fault: string | null,
} | null>("startup_failure"),
	/**
	 *  "Open data folder" on the startup error screen: the folder holding the
	 *  file at fault. Works without `AppState`.
	 */
	startupOpenDataFolder: () => __TAURI_INVOKE<null>("startup_open_data_folder"),
};

/** Events */
export const events = {
	backupCreated: makeEvent<BackupCreated>("backup-created"),
	backupFailed: makeEvent<BackupFailed>("backup-failed"),
	backupProgress: makeEvent<BackupProgress>("backup-progress"),
	exportProgress: makeEvent<ExportProgress>("export-progress"),
	gameStatusChanged: makeEvent<GameStatusChanged>("game-status-changed"),
	ingestCompleted: makeEvent<IngestCompleted>("ingest-completed"),
	installChanged: makeEvent<InstallChanged>("install-changed"),
	moveProgress: makeEvent<MoveProgress>("move-progress"),
	pricesUpdated: makeEvent<PricesUpdated>("prices-updated"),
	restoreCompleted: makeEvent<RestoreCompleted>("restore-completed"),
	restoreProgress: makeEvent<RestoreProgress>("restore-progress"),
	sessionsChanged: makeEvent<SessionsChanged>("sessions-changed"),
};

/* Types */
export type AccountMacros = {
	account: string,
	macros: Macro[],
	/**  When the file last changed (RFC 3339): "as of logout, 3 Oct". */
	modified: string | null,
};

export type AccountNode = {
	name: string,
	totals: Totals,
	/**  Account-wide files (account SavedVariables, macros, bindings…). */
	categories: CategoryNode[],
	characters: CharacterNode[],
};

/**  One staged switch: turn `addon` on or off for `character`. */
export type AddonChange = {
	addon: string,
	character: CharacterKey,
	enabled: boolean,
};

export type AddonCharacter = {
	account: string,
	/**  The group folder (Forever's opaque id, or a realm). */
	group: string,
	/**  The character folder, e.g. `Ellygie-Vargur`. */
	folder: string,
	/**
	 *  Its settings folder is a link to somewhere else, so the write gate
	 *  won't write its AddOns.txt: "linked folder" instead of a switch.
	 */
	linked: boolean,
};

export type AddonInfo = {
	/**  The folder name: the addon's name to WoW and in `AddOns.txt`. */
	name: string,
	/**  `## Title`, plain text; the folder name if there's none. */
	title: string,
	version: string | null,
	author: string | null,
	/**  `## Notes`, plain text. */
	notes: string | null,
	/**  Every value in `## Interface`. */
	interfaces: number[],
	/**  Every listed interface is below the client's. */
	out_of_date: boolean,
	/**  `## Dependencies` / `## RequiredDeps` (and other `Dep…` fields). */
	needs: string[],
	/**  The full path of its folder. */
	path: string,
	/**  One per `AddonsList::characters`, in that order. */
	enabled: boolean[],
};

export type AddonNode = {
	/**  SavedVariables file stem, e.g. "Details". */
	name: string,
	/**  Across every account and character. */
	totals: Totals,
};

export type AddonStatus = {
	/**
	 *  From the installed TOC; `None` when it isn't installed (or has no
	 *  TOC, which WoW treats the same).
	 */
	installed_version: string | null,
	/**  The version this app carries. */
	bundled_version: string,
	/**  Installed, and older than the bundled one. */
	update_available: boolean,
	/**
	 *  Character folders where it's enabled. A new addon is enabled
	 *  unless a character's `AddOns.txt` says otherwise.
	 */
	enabled_on: string[],
	/**
	 *  Character folders whose `AddOns.txt` turns it off. Reported, never
	 *  changed by the app.
	 */
	disabled_on: string[],
};

export type AddonTarget = { kind: "Account"; account: string } | { kind: "Character"; account: string; realm: string; character: string } | { kind: "Everywhere" };

export type AddonsList = {
	/**
	 *  The flavor folder, e.g. `_classic_beta_`, and its display name
	 *  ("WoW: Forever (Beta)"), for the lede.
	 */
	flavor: string,
	game: string,
	/**  The flavor's `Interface/AddOns` (full path). */
	folder: string,
	/**
	 *  The interface number this client reads (`16001` on Forever), from its
	 *  version; `None` when the version isn't known.
	 */
	interface: number | null,
	/**
	 *  The characters the "Enabled for" columns are for, in the Characters
	 *  screen's order (the WTF roster, older settings folders left out).
	 */
	characters: AddonCharacter[],
	/**  Sorted by title. */
	addons: AddonInfo[],
	/**  When this was read (RFC 3339). */
	read_at: string,
};

export type Adventure = {
	id: number,
	character_id: number,
	name: string,
	/**  File tokens, e.g. "WARRIOR" and "Human". */
	class: string | null,
	race: string | null,
	/**  RFC 3339, UTC. */
	login: string,
	logout: string | null,
	played_secs: number | null,
	/**
	 *  The zone or instance with the most time, or the top two joined
	 *  ("Stratholme & Eastern Plaguelands") when the second had at least
	 *  half as long.
	 */
	title: string,
	level_start: number | null,
	level_end: number | null,
	/**  Where the character logged out. */
	last_zone: string | null,
	/**  Zones in the order first visited. */
	travelled: string[],
	tally: Tally,
	/**  Gold through the session: login, every money point, logout. */
	money: MoneyPoint[],
	/**  Deaths, bosses, level-ups and quests, for the money chart. */
	markers: Marker[],
	timeline: Line[],
	gained: ItemLine[],
	spent: ItemLine[],
	quests: QuestLine[],
	note: string | null,
	/**  The adventures before and after this one, across characters. */
	prev: AdventureLink | null,
	next: AdventureLink | null,
};

export type AdventureLink = {
	id: number,
	name: string,
	login: string,
};

/**  The Auctionator files seen for this flavor, by their last read. */
export type AhFile = 
/**  No `Auctionator.lua` read yet. */
"none" | 
/**  At least one decoded (it may have held no prices). */
"read" | 
/**  Only files this version can't read: another format, damaged or too large. */
"unreadable";

export type AhHistory = {
	item: AhItem,
	/**  Oldest first; only days a scan saw it. */
	points: AhPoint[],
};

/**  One item with its price, for lists (search, watchlist, worth selling). */
export type AhItem = {
	item_id: number,
	/**
	 *  From the items our addon has seen; `None` for an item no character
	 *  has carried (the UI says "Item 12345").
	 */
	name: string | null,
	quality: number | null,
	/**  Its icon's FileDataID, for `icon://`. */
	icon: number | null,
	/**  The last lowest buyout (copper). */
	price: number | null,
	/**  The day it was last seen (YYYY-MM-DD). */
	last_seen: string,
	/**  Days seen in the last 30. */
	sightings: number,
	/**  The median of the daily lows over the last 30 days. */
	median: number | null,
	/**  Those daily lows, oldest first, for a sparkline. */
	recent: (number | null)[],
	/**  The median of how many were listed on those days ("typical listing"). */
	listed: number | null,
};

/**  One day on the price chart. */
export type AhPoint = {
	day: string,
	low: number | null,
	high: number | null,
	available: number | null,
};

/**  The scan bar: when Auctionator last scanned, and how many prices there are. */
export type AhStatus = {
	/**  Whether an `Auctionator.lua` with prices has been read at all. */
	has_prices: boolean,
	/**  Auctionator's realm root for the market shown ("Forever"). */
	market: string | null,
	/**  Items with a price. */
	items: number,
	/**  The newest of the last full or incremental scan (RFC 3339). */
	last_scan_at: string | null,
	/**  The newest day any price was seen (YYYY-MM-DD). */
	newest_day: string | null,
	/**
	 *  What happened to the Auctionator files, for Settings' note while
	 *  there are no prices (the AH screen and worth stay hidden until then).
	 */
	file: AhFile,
};

/**  A save on any character, for the Dashboard's "Lockouts this week". */
export type AltLockout = {
	character_id: number,
	character: string,
	/**  File token, lowercase, for the class colour. */
	class: string | null,
	lockout: Lockout,
};

/**
 *  The single error type every command returns. Serialized as
 *  `{ kind: "...", detail?: ... }` so the frontend can switch on `kind`.
 */
export type AppError = 
/**
 *  What's blocking, e.g. "WowB.exe is running", so a false positive (a
 *  tool that looks like the game) is diagnosable.
 */
{ kind: "GameRunning"; detail: string } | { kind: "NoInstall" } | { kind: "InvalidInstall"; detail: string } | { kind: "InvalidSettings"; detail: string } | { kind: "PathEscape"; detail: string } | { kind: "NotFound"; detail: string } | { kind: "Io"; detail: string } | { kind: "Unstable"; detail: string } | { kind: "Parse"; detail: {
	file: string,
	line: number,
	col: number,
	msg: string,
} } | 
/**
 *  Stored copies that can't be used. Of `files`, `missing` lists those
 *  whose copy is gone and `unreadable` those that couldn't be read right
 *  now (worth retrying); the rest don't match what was saved. Both lists
 *  hold file paths only.
 */
{ kind: "BackupCorrupt"; detail: {
	files: string[],
	missing: string[],
	unreadable: string[],
} } | 
/**
 *  Game files marked read-only (players pin e.g. Config.wtf this way).
 *  Never overridden; the user clears the flag to allow the change.
 */
{ kind: "ReadOnly"; detail: {
	paths: string[],
} } | 
/**
 *  A restore was interrupted; it must be rolled back, finished or
 *  discarded before another restore can start.
 */
{ kind: "RestorePending" } | 
/**
 *  The restore would remove files the user didn't confirm (the folder
 *  changed after the preview). Nothing was changed; preview again.
 */
{ kind: "DeletionsChanged"; detail: {
	paths: string[],
} } | { kind: "Secret"; detail: string } | { kind: "Db"; detail: string } | { kind: "Busy" } | 
/**
 *  An export can't be saved there (inside the game or backup folder,
 *  or the folder doesn't exist).
 */
{ kind: "BadDestination"; detail: string } | 
/**
 *  A data slot for our addon failed the data-only check or the size cap
 *  (bridge spec §2). Nothing in the batch was written.
 */
{ kind: "SlotRefused"; detail: string };

export type AppInfo = {
	version: string,
	paths: AppPaths,
};

/**  Where the app keeps its own files (spec §6). Never inside the game folder. */
export type AppPaths = {
	/**  settings.json */
	config_dir: string,
	/**  buddy.db and the default backups/ location (%LOCALAPPDATA% on Windows) */
	local_data_dir: string,
	log_dir: string,
};

/**
 *  An automatic backup that failed, or that left files out, for the Backups
 *  screen (R1): nobody is watching when one runs, so it's kept until a later
 *  automatic backup captures everything, and the UI asks for it on start.
 */
export type AutoBackupFailure = {
	/**  RFC 3339, UTC. */
	at: string,
	trigger: Trigger,
	/**  The error, as shown to the user. */
	error: string,
	/**
	 *  0: the backup failed. Otherwise it was taken, but this many files
	 *  couldn't be read and were left out.
	 */
	skipped?: number,
};

/**  Emitted when a snapshot has been written. */
export type BackupCreated = SnapshotSummary;

/**
 *  Emitted when an automatic backup fails (R1). The same failure stays
 *  available from `backup_auto_status` until an automatic backup succeeds.
 */
export type BackupFailed = AutoBackupFailure;

export type BackupPatch = BackupPatch_Serialize | BackupPatch_Deserialize;

export type BackupPatch_Deserialize = {
	/**  A path to use it, or null to go back to the default location. */
	location?: string | null,
	include_addons?: boolean | null,
	on_app_start?: boolean | null,
	on_game_exit?: boolean | null,
	/**  0 turns scheduled backups off. */
	schedule_hours?: number | null,
};

export type BackupPatch_Serialize = {
	/**  A path to use it, or null to go back to the default location. */
	location: string | null,
	include_addons: boolean | null,
	on_app_start: boolean | null,
	on_game_exit: boolean | null,
	/**  0 turns scheduled backups off. */
	schedule_hours: number | null,
};

/**  Emitted while a backup runs. */
export type BackupProgress = {
	done: number,
	total: number,
};

export type BackupSettings = {
	/**  None = the default, `<local_data_dir>/backups`. */
	location?: string | null,
	include_addons?: boolean,
	on_app_start?: boolean,
	on_game_exit?: boolean,
	/**
	 *  Hours between scheduled backups while the app is open; 0 = off.
	 *  Off is an explicit value so that a missing or null key always means
	 *  "use the default", never "turned off".
	 */
	schedule_hours?: number,
};

export type BagView = {
	container: number,
	name: string | null,
	size: number | null,
	free: number | null,
	items: ItemRow[],
};

export type CandidateSource = "saved" | "registry" | "common_path";

/**
 *  What a file in a character (or account) folder is for. The restore panel
 *  lets you pick these per character.
 */
export type Category = 
/**  `bindings-cache.wtf`, `macros-cache.txt` */
"BindingsMacros" | 
/**  `SavedVariables/**`, `AddOns.txt` */
"AddonSettings" | 
/**  `chat-cache.txt`, `layout-local.txt` */
"ChatLayout" | 
/**  Anything else, e.g. `config-cache.wtf` */
"Other";

export type CategoryNode = {
	category: Category,
	totals: Totals,
};

/**  One card on the Characters screen. */
export type CharacterCard = {
	id: number,
	/**
	 *  The folder identity (WTF/Account/<account>/<group>/<folder>), to
	 *  match the WTF roster's characters the addon hasn't seen yet.
	 */
	account: string,
	group_dir: string,
	folder: string,
	name: string,
	surname: string | null,
	/**  File token, lowercase (`warrior`), for the class colour. */
	class: string | null,
	race: string | null,
	level: number | null,
	realm: string | null,
	guild: string | null,
	zone: string | null,
	subzone: string | null,
	/**  The last logout we have (RFC 3339, UTC). */
	last_seen: string,
	/**  Copper. */
	money: number | null,
	xp: number | null,
	xp_max: number | null,
	rested: number | null,
	ilvl: number | null,
	/**  Seconds. */
	played: number | null,
	/**  Free slots across all bags, if the bags have been seen. */
	bag_free: number | null,
	bag_size: number | null,
	mail: number,
	bank_items: number,
	/**  Marked by the user as a bank alt (F3): a "Bank" tag on the card. */
	bank_alt: boolean,
};

/**  A character the Addons screen shows, as the UI names it back. */
export type CharacterKey = {
	account: string,
	group: string,
	folder: string,
};

export type CharacterMacros = {
	account: string,
	group: string,
	/**  The character folder, e.g. `Ellygie-Vargur`. */
	folder: string,
	macros: Macro[],
	/**  When the file last changed (RFC 3339); `None` without a file. */
	modified: string | null,
};

export type CharacterNode = {
	/**
	 *  The folder above the character: Forever's opaque group id (`70`) or,
	 *  in older folders, the realm. Identity only, never shown.
	 */
	realm: string,
	/**  The character folder as written (`Ellygie-Vargur`), never split. */
	name: string,
	/**
	 *  An older settings folder, the layout from before surnames
	 *  (`install::wtf::older_groups`): listed apart, fully restorable.
	 */
	older: boolean,
	totals: Totals,
	categories: CategoryNode[],
};

/**  One character folder: `WTF/Account/<account>/<realm>/<name>`. */
export type CharacterRef = {
	account: string,
	/**
	 *  The folder between account and character. On Forever it's an opaque
	 *  group id (`70`); in the older layout it's the realm. Part of the
	 *  identity only, never shown. (Kept as `realm` so stored sessions
	 *  still read.)
	 */
	realm: string,
	/**
	 *  The character folder as written: the full name, with a surname as
	 *  `Ellygie-Vargur`. Never split; the UI shows it as "Ellygie Vargur".
	 */
	name: string,
};

export type CharacterSheet = {
	card: CharacterCard,
	equipped: ItemRow[],
	bags: BagView[],
	bank: Visited,
	mail: MailView,
	professions: ProfessionRow[],
	/**  Saves that haven't reset, soonest reset first. */
	lockouts: Lockout[],
	/**
	 *  The login the saves were read at (RFC 3339); `None` if they never
	 *  have been, as opposed to read and none found.
	 */
	lockouts_as_of: string | null,
	/**  The last 30 days of gold, oldest first. */
	gold_30d: GoldPoint[],
};

export type CharactersOverview = {
	/**  Copper, across every character. */
	gold: number | null,
	/**  Items carried, across bags, bank and mail. */
	items: number,
	characters: CharacterCard[],
};

export type Chart = {
	/**  One per calendar day, oldest first, "2026-10-04". */
	days: string[],
	/**  The top characters by gold now, then "N others" summed, if any. */
	series: Series[],
	/**  Every character added up, per day. */
	account: (number | null)[],
};

/**  How sure a price is, from how often and how lately it was seen. */
export type Confidence = "sure" | "fair" | "rough";

/**
 *  What `install_detect` returns: every install found, plus every place we
 *  looked, so onboarding's "not found" state can say where.
 */
export type DetectReport = {
	candidates: InstallCandidate[],
	looked_in: LookedIn[],
};

export type Earner = {
	character_id: number,
	name: string,
	gained: number | null,
	/**  Adventures in the same 30 days. */
	sessions: number,
};

/**  Emitted while an export runs. */
export type ExportProgress = {
	done: number,
	total: number,
};

/**  What an export wrote. */
export type ExportReport = {
	snapshot_id: string,
	/**  Where the zip was saved (`.zip` is added if the name lacked it). */
	path: string,
	files: number,
	/**  Size of the zip. */
	bytes: number | null,
};

/**  One `_<name>_` folder under the root. */
export type Flavor = {
	/**  Folder name, e.g. "_classic_beta_". */
	id: string,
	/**  Display name, e.g. "WoW: Forever (Beta)". */
	label: string,
	/**  Battle.net product code from `.build.info`, e.g. "wow_classic_beta". */
	product: string | null,
	/**  Client version from `.build.info`, e.g. "1.60.0.63105". */
	version: string | null,
	is_forever: boolean,
	dir: string,
	exe: string | null,
	has_wtf: boolean,
	/**  Account folder names under `WTF/Account`. */
	accounts: string[],
	/**
	 *  Character folders under `WTF/Account/<account>/<group>/`. Forever
	 *  writes `<group>` as an opaque id (`70`) and the character folder as
	 *  the full name, `Ellygie-Vargur` with a surname; older folders are
	 *  `<Realm>/<Name>`. Next to the new layout, those are older settings
	 *  folders and aren't counted (`wtf::older_groups`). Neither folder is a
	 *  realm or ruleset to show (probe run 1, matrix fact 5).
	 */
	characters: number,
	/**
	 *  `WTF` or `Interface/AddOns` when they're symlinks or junctions, as
	 *  recorded by `GameRoot`. Allowed, and shown as info ("WTF is linked
	 *  to D:\Sync\WTF").
	 */
	links: LinkedFolder[],
};

/**  The folders the UI can reveal. A fixed set: the frontend never passes a path. */
export type FolderTarget = "backups" | "logs" | 
/**  The active flavor folder, e.g. `<root>/_classic_beta_`. */
"game" | 
/**
 *  Its `Interface/AddOns`. Never created by the app: if it isn't there,
 *  opening it fails.
 */
"addons";

export type GameStatus = {
	running: boolean,
	pids: number[],
	/**  When the game was first seen running (RFC 3339, UTC), for "session 1h 42m". */
	since: string | null,
	/**
	 *  The last poll couldn't list processes, so `running` is stale. The UI
	 *  says it can't tell; restores stay locked.
	 */
	unknown: boolean,
};

/**  Emitted when WoW starts or stops. */
export type GameStatusChanged = GameStatus;

export type GoldPoint = {
	at: string,
	money: number | null,
};

/**
 *  What the goods the alts carry are worth (F5c): bags, bank and mail, not
 *  gear, at the last lowest buyout. Only priced items count; the rest is
 *  counted apart, so a net worth never pretends to be complete.
 */
export type GoodsWorth = {
	/**  Copper, across every character. */
	value: number | null,
	/**  Items carried, and how many of them have a price. */
	items: number,
	priced: number,
	/**  Per character, `(character id, copper)`, for "Worth carried". */
	by_character: ([number, number | null])[],
	/**  The most valuable holdings, most first (up to five). */
	top: Holdings[],
	/**  The newest scan the prices come from (RFC 3339). */
	as_of: string | null,
};

/**  Where some of an item is, for "Coinpurse · bank". */
export type Holding = {
	character_id: number,
	character: string,
	class: string | null,
	/**  `bag`, `bank` or `mail`. */
	location: string,
	count: number,
};

/**  One of the most valuable holdings, for the Ledger's net worth panel. */
export type Holdings = {
	item: AhItem,
	count: number,
	value: number | null,
};

/**  Settings > Game data cache. */
export type IconCacheStatus = {
	files: number,
	bytes: number | null,
	/**
	 *  The game build icons come from ("1.60.1.70205"); `None` when the
	 *  game's data can't be read (no install, or not a CASC install).
	 */
	build: string | null,
	/**
	 *  This build's art files couldn't be read: the storage wouldn't open,
	 *  or reads failed on damaged data with nothing read and none cached.
	 *  Icons not downloaded yet, encrypted or not in the build don't count:
	 *  those are one icon's letter, not a problem reading the game.
	 */
	unreadable: boolean,
};

/**  What a rebuild read. */
export type IconFill = {
	read: number,
	failed: number,
};

/**  Emitted after a scan or replay that changed characters' data. */
export type IngestCompleted = {
	/**  `characters.id` (u32: row ids, and specta refuses i64 in TypeScript). */
	characters: number[],
};

/**
 *  A character's file that couldn't be read last time, for the Dashboard's
 *  "Couldn't read Thrandor's notes · will retry".
 */
export type IngestProblem = {
	/**  The character folder, e.g. `Ellygie-Vargur`. */
	character: string,
	/**  `skipped (parse)`, `skipped (integrity)` or `skipped (mismatch)`. */
	status: string,
	/**  Names the field at fault, never a value from the file. */
	error: string | null,
};

/**  A WoW root folder and the game flavors found in it. */
export type Install = {
	root: string,
	flavors: Flavor[],
	/**  Folder name of the active flavor, once one is chosen. */
	active: string | null,
};

/**
 *  A validated install found by detection. `install.active` is set when a
 *  flavor can be chosen without asking.
 */
export type InstallCandidate = {
	install: Install,
	source: CandidateSource,
};

/**  Emitted when the active install is set or resolved at startup. */
export type InstallChanged = {
	install: Install | null,
};

export type InstallChoice = {
	root: string,
	/**  Flavor folder name, e.g. "_classic_beta_". */
	flavor: string,
	/**
	 *  Where the flavor's linked folders (WTF, Interface/AddOns) pointed when
	 *  the user confirmed this install. Recorded once by `install::set`; game
	 *  paths are checked against these, so a link re-pointed later is refused
	 *  instead of silently followed.
	 */
	links?: LinkedFolder[],
};

/**
 *  The only keys the app stores. A closed enum, so the frontend can't write
 *  arbitrary keychain entries.
 */
export type IntegrationId = "curseforge" | "wago" | "wago_io" | "github" | "battlenet_client_id" | "battlenet_client_secret";

export type IntegrationSetting = {
	enabled?: boolean,
};

/**  A closed set: each optional integration is a named field, never a free-form key. */
export type Integrations = {
	curseforge?: IntegrationSetting,
	wago?: IntegrationSetting,
	wago_io?: IntegrationSetting,
	github?: IntegrationSetting,
	battlenet?: IntegrationSetting,
};

export type IntegrationsPatch = {
	curseforge?: IntegrationSetting | null,
	wago?: IntegrationSetting | null,
	wago_io?: IntegrationSetting | null,
	github?: IntegrationSetting | null,
	battlenet?: IntegrationSetting | null,
};

export type ItemLine = {
	item_id: number,
	name: string,
	quality: number | null,
	/**  Its icon's FileDataID, for `icon://`. */
	icon?: number | null,
	count: number,
	/**
	 *  sold | used | mailed for what was spent; bought | mail for a gain
	 *  that didn't drop; `None` for loot.
	 */
	how: string | null,
	/**  The character wears one now (the recap's Worth reads "equipped"). */
	equipped?: boolean,
};

/**  One item in a slot, ready to show. */
export type ItemRow = {
	container: number,
	slot: number,
	item_id: number,
	name: string,
	/**  0 poor … 5 legendary, when known. */
	quality: number | null,
	ilvl: number | null,
	/**  Its icon's FileDataID, for `icon://` (see `icons`). */
	icon: number | null,
	count: number,
	/**
	 *  When this character last looted one (RFC 3339), if the journal has
	 *  it, and the zone it was in. Never a source (IMPLEMENTING.md §7).
	 */
	looted_at: string | null,
	looted_in: string | null,
};

/**  An interrupted restore: enough to roll it back or run it again. */
export type Journal = {
	/**  The snapshot the user chose to restore. */
	source_snapshot: string,
	/**
	 *  Taken before the user's restore changed anything. Rolling back always
	 *  restores this one, even after an interrupted recovery.
	 */
	original_pre_restore: string,
	/**
	 *  Taken before the latest attempt (the restore, or a recovery of it).
	 *  Equal to `original_pre_restore` on the first attempt.
	 */
	pre_restore_snapshot: string,
	selection: RestoreSelection,
	mode: RestoreMode,
	flavor: string,
	started_at: string,
	/**  The restore's one-line summary, for the recovery prompt. */
	summary: string,
};

/**  What to do about a restore that was interrupted. */
export type JournalAction = 
/**  Put back what was there before the restore started (recommended). */
"roll_back" | 
/**  Run the restore again to completion. */
"finish" | 
/**
 *  Forget it without changing files (e.g. the journal is unreadable).
 *  Its pre-restore snapshot stays in the Safety list.
 */
"discard";

export type JournalEntry = {
	adventure_id: number,
	character_id: number,
	name: string,
	login: string,
	logout: string | null,
	played_secs: number | null,
	gold_delta: number | null,
	/**  The level reached, if the character levelled. */
	level: number | null,
	of_note: OfNote | null,
};

/**
 *  Money is copper, as `f64` so TypeScript can hold it safely (specta sends
 *  no `i64`). Times are RFC 3339, UTC.
 */
export type Ledger = {
	/**
	 *  The earliest gold point ("from every logout since 2 Sep"); `None`
	 *  until the addon has written anything.
	 */
	since: string | null,
	tiles: Tiles,
	chart: Chart,
	journal: JournalEntry[],
};

export type LedgerExport = 
/**  The chart as a table: a row per day, a column per character. */
"gold" | 
/**  The journal: a row per adventure. */
"journal";

export type LedgerRange = "week" | "month" | "quarter" | "all";

export type Line = {
	at: string,
	/**  login | zone | death | repair | encounter | level | quest | loot | logout */
	kind: string,
	text: string,
	detail: string | null,
	/**  For an item line, its quality (the letter tile's colour). */
	quality: number | null,
	/**  The client withholds part of this (a killer, a loot source). */
	withheld: boolean,
};

export type LinkedFolder = {
	/**  `/`-separated path relative to the game root, e.g. "WTF". */
	folder: string,
	/**
	 *  Canonical target recorded at validation, e.g. `D:\Dropbox\WTF`.
	 *  The UI shows it as "WTF is linked to …".
	 */
	target: string,
};

/**  A raid or dungeon save that hasn't reset yet (F3). */
export type Lockout = {
	/**  The instance, as the game names it ("Molten Core"). */
	name: string,
	/**  "Normal", "Heroic", … as the game gives it; may be empty. */
	difficulty: string,
	raid: boolean,
	/**  When the save resets (RFC 3339), if the game said. */
	reset_at: string | null,
};

export type LookedIn = {
	source: CandidateSource,
	path: string,
};

export type Macro = {
	name: string,
	/**  A texture name (`INV_Misc_QuestionMark`) or an icon file id. */
	icon: string,
	/**  Lines joined with `\n`. */
	body: string,
	/**
	 *  The body's length as the game counts it (bytes), against
	 *  `MACRO_MAX`.
	 */
	length: number,
};

export type MacrosList = {
	/**  The flavor folder, e.g. `_classic_beta_`. */
	flavor: string,
	/**  One per account folder, in name order. */
	accounts: AccountMacros[],
	/**
	 *  One per character on the WTF roster (older settings folders left
	 *  out), in the Characters screen's order, macros or not.
	 */
	characters: CharacterMacros[],
	/**  The longest body the game allows. */
	max: number,
};

export type MailRow = {
	/**  Other players' text from your own mailbox: shown here, never exported. */
	sender: string | null,
	subject: string | null,
	money: number | null,
	cod: number | null,
	days_left: number | null,
	items: ItemRow[],
};

export type MailView = {
	as_of: string | null,
	messages: MailRow[],
};

export type Marker = {
	at: string,
	/**  death | encounter | level | quest */
	kind: string,
	label: string,
};

export type MoneyPoint = {
	at: string,
	money: number | null,
};

/**  Emitted while the backups are copied to a new folder. */
export type MoveProgress = {
	done: number,
	total: number,
};

/**  What a move did, for the Settings screen. */
export type MoveReport = {
	/**  The store's folder now. */
	dir: string,
	files: number,
	bytes: number | null,
	/**
	 *  The old folder, if removing it failed after the move. The backups
	 *  are safe in the new one; this is a leftover copy to delete by hand.
	 */
	left_behind: string | null,
};

/**
 *  The journal's "Of note" (spec §5): a level-up, else the zone with the most
 *  time and the quest count, else the biggest gain.
 */
export type OfNote = {
	text: string,
	/**  For an item: its quality, for the letter tile's colour. */
	quality: number | null,
	/**  For an item: its icon's FileDataID, for `icon://`. */
	icon?: number | null,
};

/**  Files to write in one folder, for "…\Thrandor\SavedVariables\ (41 files)". */
export type PlanFolder = {
	/**  Relative to the flavor folder, `/`-separated. */
	folder: string,
	files: string[],
	bytes: number | null,
};

export type PlaySession = {
	/**
	 *  A row id; `u32` because specta won't send an `i64` to TypeScript, and
	 *  four billion sessions is plenty.
	 */
	id: number,
	flavor: string,
	/**  RFC 3339, UTC. */
	started_at: string,
	/**  `None` while WoW is still running. */
	ended_at: string | null,
	/**
	 *  Who played. With the addon (V9): the characters whose adventures
	 *  started during the session, in login order, for certain. Without it:
	 *  the characters whose settings changed, in WTF folder order. Empty
	 *  while running, or if nothing changed (e.g. WoW was closed at
	 *  character select).
	 */
	characters: CharacterRef[],
	/**
	 *  The addon's adventures in this session, in login order, so the
	 *  Recent sessions row can open their recaps. Empty without the addon.
	 */
	adventures: number[],
	/**
	 *  WoW wrote a crash report (`<flavor>/Errors`) during the run. A process
	 *  killed without one can't be told apart from a clean exit.
	 */
	crashed: boolean,
};

/**  Emitted after new prices were read. */
export type PricesUpdated = {
	/**  Items with a price now. */
	items: number,
};

export type ProfessionRow = {
	name: string,
	skill: number | null,
	max: number | null,
};

/**  What a prune did. */
export type PruneReport = {
	pruned: string[],
	blobs_removed: number,
	freed_bytes: number | null,
	/**  Store size on disk afterwards. */
	used_bytes: number | null,
	budget_bytes: number | null,
	/**
	 *  Still over budget after pruning everything allowed (only manual,
	 *  pinned or the newest few are left): the UI shows a warning.
	 */
	over_budget: boolean,
};

/**
 *  One accept or turn-in. Everything but the time and kind is optional:
 *  older addons recorded only the id and title, and the place is missing
 *  inside instances.
 */
export type QuestEntry = {
	/**  RFC 3339, UTC. */
	at: string,
	kind: QuestKind,
	quest_id: number | null,
	title: string | null,
	zone: string | null,
	/**  The NPC it was taken from or handed to; never another player. */
	giver: string | null,
	/**  uiMapID, and the position on it (0 to 1). */
	map: number | null,
	x: number | null,
	y: number | null,
};

export type QuestKind = "accepted" | "turned_in";

export type QuestLine = {
	title: string,
	/**  The zone the character was in when they turned it in. */
	zone: string | null,
};

export type QuestLog = {
	/**  Quests completed, as of `done_as_of`; 0 before an addon that reports it. */
	done: number,
	/**  When the addon last listed them (RFC 3339, UTC). */
	done_as_of: string | null,
	/**  Newest first. */
	entries: QuestEntry[],
};

/**  What the UI shows about interrupted restores. */
export type RecoveryStatus = 
/**  No interrupted restore. */
{ kind: "none" } | 
/**  Roll back, finish or leave as is. */
{ kind: "pending"; journal: Journal } | 
/**
 *  A journal exists but can't be read, so roll back and finish aren't
 *  possible. `latest_safety` is the newest pre-restore snapshot, for
 *  "Open the safety copy"; clearing the notice discards the journal.
 */
{ kind: "unreadable"; error: string; latest_safety: string | null };

/**
 *  A path relative to a base folder (usually the flavor dir) that can't name
 *  anything outside it (spec §4). Stored as components and written with `/`,
 *  which is also the format backup manifests use (`WTF/Account/X/...`).
 * 
 *  Rejected: empty paths, absolute paths, drive (`C:`) and UNC prefixes, `.`
 *  and `..`, `:` anywhere (drives, NTFS alternate data streams), NUL,
 *  components ending in a dot or space (Windows strips those, so `a.` would
 *  alias `a`), and DOS device names like `CON` or `com1.txt`.
 */
export type RelPath = string;

/**  Emitted when a restore (or a recovery) has finished. */
export type RestoreCompleted = RestoreReport;

/**
 *  Overlay writes the snapshot's files and leaves others alone (the default
 *  for every scope). Mirror also removes files under the scope that the
 *  snapshot doesn't have.
 */
export type RestoreMode = "overlay" | "mirror";

export type RestorePlan = {
	snapshot_id: string,
	mode: RestoreMode,
	write: PlanFolder[],
	write_count: number,
	/**  Shown prominently, with its own count, in the confirm dialog. */
	delete: string[],
	/**  Files that already match the snapshot. */
	unchanged: number,
	bytes: number | null,
	/**
	 *  Targets marked read-only. The restore refuses until the flag is
	 *  cleared; players do this on purpose (e.g. to pin Config.wtf).
	 */
	read_only: string[],
	/**
	 *  Files (or folders) in the selection that the snapshot couldn't read
	 *  at the time: not in this backup, so left as they are, never deleted.
	 */
	not_backed_up: string[],
	/**  "keybindings, macros and 41 addon settings". */
	summary: string,
};

/**  Emitted while a restore runs. */
export type RestoreProgress = {
	done: number,
	total: number,
};

export type RestoreReport = {
	snapshot_id: string,
	/**
	 *  The safety snapshot taken before anything changed; `None` if there
	 *  was nothing to do.
	 */
	pre_restore_snapshot: string | null,
	written: number,
	deleted: number,
	summary: string,
};

/**  What to restore. A file is restored if any item matches it. */
export type RestoreSelection = {
	items: ScopeItem[],
};

export type Scope = 
/**  The whole tree that backups cover. */
"full" | 
/**  Only specific paths (safety snapshots before a write). */
"partial";

export type ScopeItem = 
/**  Every file in the snapshot. */
{ kind: "Everything" } | 
/**  Account-wide files (not its characters). `None` = every category. */
{ kind: "Account"; account: string; categories: Category[] | null } | 
/**  One character's folder. `None` = every category. */
{ kind: "Character"; account: string; realm: string; character: string; categories: Category[] | null } | 
/**  One addon's SavedVariables (`<addon>.lua` and `.lua.bak`). */
{ kind: "AddonData"; addon: string; target: AddonTarget } | 
/**  Exact files or folders, relative to the flavor folder. */
{ kind: "Paths"; paths: RelPath[] };

/**  One item stack total on one character, in one place. */
export type SearchHit = {
	character_id: number,
	/**  "Velyra Duskmane". */
	character: string,
	class: string | null,
	/**  `bag`, `bank` or `mail`. */
	location: string,
	item_id: number,
	name: string,
	quality: number | null,
	ilvl: number | null,
	icon: number | null,
	/**  Summed over every stack of it in that place. */
	count: number,
	/**
	 *  Bank and mail: when that place was last seen (RFC 3339), for "As of
	 *  your last bank visit". Satchels are as of the last logout: `None`.
	 */
	as_of: string | null,
};

export type SearchResults = {
	/**  Most first, at most `SEARCH_MAX`. */
	hits: SearchHit[],
	/**  Items matched, across every hit (shown or not). */
	total: number,
	/**  Characters with a match, to light their cards. */
	characters: number[],
	/**  More hits than `hits` holds. */
	more: boolean,
};

/**
 *  One row of the Integrations panel. Each id is checked on its own, so one
 *  unreadable credential shows as that row's error instead of failing all.
 */
export type SecretStatus = {
	id: IntegrationId,
	is_set: boolean,
	/**  Why the store couldn't be read for this id. Never contains the value. */
	error: string | null,
};

export type Sellable = {
	item: AhItem,
	count: number,
	/**  Most first. */
	holdings: Holding[],
	/**  count × price (copper). */
	value: number | null,
	confidence: Confidence,
	/**
	 *  Why a price is rough: "few" (under 5 sightings) or "stale" (not seen
	 *  for over a week).
	 */
	caution: string | null,
};

export type Series = {
	/**  `None` for the "others" line. */
	character_id: number | null,
	name: string,
	/**  How many characters the "others" line adds up; 1 for a character. */
	count: number,
	/**  Per day; `None` before the character's first point. */
	values: (number | null)[],
};

/**  Emitted when a session starts, ends, or learns its characters. */
export type SessionsChanged = null;

/**
 *  settings.json (spec §6). Every field has a default, so a missing key never
 *  fails a load. Keys this build doesn't know are kept on disk by
 *  `SettingsStore`, at any depth, so a downgrade never wipes them.
 */
export type Settings = {
	/**  Backend-owned: set by load/migrate, ignored on update. */
	schema_version?: number,
	/**  Backend-owned: changed only through install commands, which validate it. */
	install?: InstallChoice | null,
	backup?: BackupSettings,
	/**  Extra game process names to treat as WoW, e.g. if Forever's exe has an unusual name. */
	process_names_extra?: string[],
	integrations?: Integrations,
	/**
	 *  "Show item icons from my game files" (F8c). Off by default: reading
	 *  the game's art archive is the user's choice, and while it's off the
	 *  app never opens the game's `Data` folder.
	 */
	item_icons?: boolean,
	/**
	 *  Free-form UI preferences (remembered tabs, filters). The backend never reads it.
	 *  Strings only; the frontend JSON-encodes anything structured.
	 */
	ui?: { [key in string]: string },
};

/**
 *  A partial update from the UI (spec §8 `settings_update(patch)`): only the
 *  fields present change, so a stale copy of the settings can't overwrite
 *  newer values. There are no `install` or `schema_version` fields, and
 *  unknown fields are rejected, so a patch can't touch backend-owned state.
 */
export type SettingsPatch = SettingsPatch_Serialize | SettingsPatch_Deserialize;

/**
 *  A partial update from the UI (spec §8 `settings_update(patch)`): only the
 *  fields present change, so a stale copy of the settings can't overwrite
 *  newer values. There are no `install` or `schema_version` fields, and
 *  unknown fields are rejected, so a patch can't touch backend-owned state.
 */
export type SettingsPatch_Deserialize = {
	backup?: BackupPatch_Deserialize | null,
	process_names_extra?: string[] | null,
	integrations?: IntegrationsPatch | null,
	item_icons?: boolean | null,
	/**  Set keys to a string to store them, or to null to remove them. */
	ui?: { [key in string]: string | null } | null,
};

/**
 *  A partial update from the UI (spec §8 `settings_update(patch)`): only the
 *  fields present change, so a stale copy of the settings can't overwrite
 *  newer values. There are no `install` or `schema_version` fields, and
 *  unknown fields are rejected, so a patch can't touch backend-owned state.
 */
export type SettingsPatch_Serialize = {
	backup: BackupPatch_Serialize | null,
	process_names_extra: string[] | null,
	integrations: IntegrationsPatch | null,
	item_icons: boolean | null,
	/**  Set keys to a string to store them, or to null to remove them. */
	ui: { [key in string]: string | null } | null,
};

/**  A file a full snapshot left out, and why. */
export type SkippedFile = {
	/**
	 *  Relative to the flavor folder when it could be expressed that way;
	 *  otherwise the path as the OS reported it.
	 */
	path: string,
	reason: string,
};

export type SnapshotDetail = {
	summary: SnapshotSummary,
	accounts: AccountNode[],
	addons: AddonNode[],
	/**  Files outside `WTF/Account` (e.g. `WTF/Config.wtf`, AddOns folders). */
	other: Totals,
	/**  Files the snapshot couldn't capture and left out (R1). */
	skipped: SkippedFile[],
};

export type SnapshotKind = "Manual" | "Auto" | "Safety";

/**  One row of the Backups list. */
export type SnapshotSummary = {
	id: string,
	created_at: string,
	trigger: Trigger,
	kind: SnapshotKind,
	label: string | null,
	pinned: boolean,
	scope: Scope,
	flavor: string,
	game_running: boolean,
	file_count: number,
	char_count: number,
	addon_count: number,
	/**
	 *  Bytes are f64 because TypeScript numbers can't hold a u64 safely;
	 *  exact up to 9 PB.
	 */
	total_bytes: number | null,
	new_bytes: number | null,
};

export type StartupFailure = {
	problem: StartupProblem,
	/**  The error, for "Error details" and "Copy error details". */
	message: string,
	paths: AppPaths,
	/**  The file at fault, shown in red; `None` if it isn't one file. */
	at_fault: string | null,
};

/**  Which of the app's files is the problem, so the UI can mark it. */
export type StartupProblem = 
/**  `buddy.db`, e.g. written by a newer version of the app. */
"database" | 
/**  `settings.json`. */
"settings" | 
/**  Anything else, e.g. a data folder that can't be created. */
"other";

/**  The storage meter on the Backups screen. */
export type StorageInfo = {
	used_bytes: number | null,
	budget_bytes: number | null,
	over_budget: boolean,
	/**  Generated from the policy, shown as is (spec §5). */
	retention_summary: string,
	/**
	 *  Cleanup is refused because a snapshot's record is damaged (which
	 *  one, and why), so the budget isn't being enforced. Shown as a warning.
	 */
	cleanup_blocked: string | null,
};

/**  Money is copper, as `f64` (specta sends no `i64`). */
export type Tally = {
	gold: number | null,
	/**
	 *  Only when the level didn't change: across a level the client's XP
	 *  numbers restart, and the addon doesn't record the old maximum.
	 */
	xp: number | null,
	/**
	 *  XP from quest rewards, which is known even across a level-up (the
	 *  tally shows it when `xp` isn't).
	 */
	quest_xp: number | null,
	/**  Items looted (not bought or taken from mail). */
	loot: number,
	deaths: number,
	repairs: number | null,
};

export type Tiles = {
	/**  Every character's latest money, added up. */
	account_gold: number | null,
	characters: number,
	/**
	 *  What the account gained (or lost) over 30 and 7 days. A character
	 *  first seen inside the window counts from its first point, so a new
	 *  character's starting gold isn't "earned".
	 */
	last_30_days: number | null,
	this_week: number | null,
	best_earner: Earner | null,
};

/**
 *  What Apply did, for "4 changes applied. A safety snapshot was taken
 *  first." with Undo.
 */
export type ToggleResult = {
	/**
	 *  The safety snapshot taken first; `None` if every file already said
	 *  so and nothing was written.
	 */
	snapshot_id: string | null,
	/**  Changes that took effect (ones already so are left out). */
	applied: number,
};

export type Totals = {
	files: number,
	/**  f64 so TypeScript can hold it safely. */
	bytes: number | null,
};

export type Trigger = "manual" | "app_start" | "game_exit" | "scheduled" | "pre_write" | "pre_restore";

export type VerifyReport = {
	snapshot_id: string,
	files: number,
	/**  Files whose stored copy is missing, unreadable or fails its checksum. */
	corrupt: string[],
	/**  Those of `corrupt` whose stored copy is gone. */
	missing: string[],
	/**  Those of `corrupt` whose copy couldn't be read right now (retry). */
	unreadable: string[],
};

/**  A location the addon only sees when it's opened (bank, mailbox). */
export type Visited = {
	/**  When it was last seen (RFC 3339), `None` if never. */
	as_of: string | null,
	bags: BagView[],
};

/**  A character found in the WTF folder. */
export type WtfCharacter = {
	/**
	 *  When any file in its folder last changed (RFC 3339, UTC): close to
	 *  when it was last logged out.
	 */
	last_played: string | null,
	/**
	 *  An older settings folder: the layout from before surnames, next to
	 *  the new one (`install::wtf::older_groups`). Listed apart, not counted,
	 *  and never a session's character.
	 */
	older: boolean,
} & CharacterRef;

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

