// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  App version and data locations, for the Settings/about panel and bug reports. */
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	appOpenFolder: (which: FolderTarget) => __TAURI_INVOKE<null>("app_open_folder", { which }),
	/**  Looks for WoW installs on this machine (registry, common paths), for onboarding. */
	installDetect: () => __TAURI_INVOKE<InstallCandidate[]>("install_detect"),
	/**
	 *  The install the app is working with, or `None` if none is set or the saved
	 *  folder can't be found right now.
	 */
	installGet: () => __TAURI_INVOKE<{
	root: string,
	flavor: Flavor,
} | null>("install_get"),
	/**
	 *  Validates and saves the game folder. `path` may be the WoW root, a flavor
	 *  folder or a WTF folder (from the folder picker or a detected candidate);
	 *  `flavor` picks the game folder when the root has several.
	 */
	installSet: (path: string, flavor: string | null) => __TAURI_INVOKE<ActiveInstall>("install_set", { path, flavor }),
	settingsGet: () => __TAURI_INVOKE<Settings>("settings_get"),
	/**
	 *  Saves a full settings object (typically `settings_get()` with edits).
	 *  `schema_version` and `install` are backend-owned and ignored here; the game
	 *  folder is changed through the install commands, which validate it.
	 */
	settingsUpdate: (settings: Settings) => __TAURI_INVOKE<Settings>("settings_update", { settings }),
};

/** Events */
export const events = {
	installChanged: makeEvent<InstallChanged>("install-changed"),
};

/* Types */
/**  The install the app is working with: the root plus the chosen flavor. */
export type ActiveInstall = {
	root: string,
	flavor: Flavor,
};

/**
 *  The single error type every command returns. Serialized as
 *  `{ kind: "...", detail?: ... }` so the frontend can switch on `kind`.
 */
export type AppError = { kind: "GameRunning" } | { kind: "NoInstall" } | { kind: "InvalidInstall"; detail: string } | { kind: "InvalidSettings"; detail: string } | { kind: "PathEscape"; detail: string } | { kind: "NotFound"; detail: string } | { kind: "Io"; detail: string } | { kind: "Unstable"; detail: string } | { kind: "Parse"; detail: {
	file: string,
	line: number,
	col: number,
	msg: string,
} } | { kind: "BackupCorrupt"; detail: {
	files: string[],
} } | { kind: "Secret"; detail: string } | { kind: "Db"; detail: string } | { kind: "Busy" };

export type AppInfo = {
	version: string,
	paths: AppPaths,
};

/**  Where the app keeps its own files (spec §6). Never inside the game folder. */
export type AppPaths = {
	/**  settings.json */
	config_dir: string,
	/**  buddy.db and the default backups/ location (%LOCALAPPDATA% on Windows) */
	local_data_dir: string,
	log_dir: string,
};

export type BackupSettings = {
	/**  None = the default, `<local_data_dir>/backups`. */
	location?: string | null,
	include_addons?: boolean,
	on_app_start?: boolean,
	on_game_exit?: boolean,
	/**  None = no scheduled backups. */
	schedule_hours?: number | null,
};

export type CandidateSource = "Registry" | "CommonPath";

/**  One `_<flavor>_` folder, e.g. `_classic_beta_`. */
export type Flavor = {
	/**  Folder name, e.g. "_classic_beta_". This is what settings store. */
	id: string,
	label: string,
	is_forever: boolean,
	/**  Battle.net product code from `.build.info`, e.g. "wow_classic_beta". */
	product: string | null,
	/**  Client version from `.build.info`, e.g. "1.60.0.63105". */
	version: string | null,
	dir: string,
	exe: string | null,
	has_wtf: boolean,
	accounts: string[],
};

/**
 *  The folders the UI may reveal in Explorer/Finder. A fixed set, so the
 *  frontend never gets to open arbitrary paths.
 */
export type FolderTarget = "Backups" | "Logs" | "AppData" | "GameFolder";

/**  A validated WoW root folder and the game flavors installed in it. */
export type Install = {
	root: string,
	/**  Forever first, then alphabetical by label. */
	flavors: Flavor[],
};

export type InstallCandidate = {
	install: Install,
	source: CandidateSource,
};

/**  Emitted whenever the active install changes. */
export type InstallChanged = ActiveInstall | null;

export type InstallChoice = {
	root: string,
	/**  Flavor folder name, e.g. "_classic_beta_". */
	flavor: string,
};

export type IntegrationSetting = {
	enabled?: boolean,
};

/**  A closed set: each optional integration is a named field, never a free-form key. */
export type Integrations = {
	curseforge?: IntegrationSetting,
	wago?: IntegrationSetting,
	wago_io?: IntegrationSetting,
	github?: IntegrationSetting,
	battlenet?: IntegrationSetting,
};

/**
 *  settings.json (spec §6). Every field has a default, so a missing key never
 *  fails a load. Keys this build doesn't know are kept on disk by
 *  `SettingsStore`, at any depth, so a downgrade never wipes them.
 */
export type Settings = {
	/**  Backend-owned: set by load/migrate, ignored on update. */
	schema_version?: number,
	/**  Backend-owned: changed only through install commands, which validate it. */
	install?: InstallChoice | null,
	backup?: BackupSettings,
	/**  Extra game process names to treat as WoW, e.g. if Forever's exe has an unusual name. */
	process_names_extra?: string[],
	integrations?: Integrations,
	/**
	 *  Free-form UI preferences (remembered tabs, filters). The backend never reads it.
	 *  Strings only; the frontend JSON-encodes anything structured.
	 */
	ui?: { [key in string]: string },
};

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

